[book]
authors = ["Alex Pedley"]
language = "en"
multilingual = false
src = "src"
title = "passc documentation"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
site-url = "/passc/"
git-repository-url = "https://github.com/alecks/passc"
